---
- name: Install deps
  apt: name={{ item }}  state=present
  with_items:
    - python-pip
    - build-essential

- name: Install docker
  apt: name=docker.io state=present
  notify:
    - restart docker

- name: Installing Python depencies
  pip: name=docker-py

